name: flutter_redirectly
description: A Flutter plugin for Redirectly dynamic links - similar to Firebase
  Dynamic Links but using your own backend.

version: 2.1.7

homepage: https://redirectly.app
repository: https://github.com/redirectly-app/flutter_redirectly
issue_tracker: https://github.com/redirectly-app/flutter_redirectly/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  app_links: ^6.4.1
  flutter:
    sdk: flutter
  http: ^1.6.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
